apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app08
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/shroqkf/todo-app08.git
    targetRevision: HEAD
    path: .
    kustomize:
      namePrefix: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true